{% set name = "fasttreeshap" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fasttreeshap-{{ version }}.tar.gz
  sha256: cea11b3122f7e41eb90730547a6a0c34c5be6baf7798677fd7a4c3d3b4ab8e6d

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - numpy <1.22
    - pip
    - python
  run:
    - cloudpickle
    - numba
    - numpy <1.22
    - packaging >20.9
    - pandas
    - psutil
    - python
    - scikit-learn
    - scipy
    - shap
    - slicer ==0.0.7
    - tqdm >4.25.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - fasttreeshap
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/linkedin/fasttreeshap
  summary: A fast implementation of TreeSHAP algorithm.
  license: BSD-2-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
