{% set name = "fasttreeshap" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fasttreeshap-{{ version }}.tar.gz
  sha256: 03e4ebb57e6ca2e869848f79f0d3750831a22951fa00033ad1551c9ba9c1a954

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - numpy
    - pip
    - python
  run:
    - cloudpickle
    - numba
    - numpy
    - packaging >20.9
    - pandas
    - psutil
    - python
    - scikit-learn
    - scipy
    - shap
    - slicer ==0.0.7
    - tqdm >4.25.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - fasttreeshap
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/linkedin/fasttreeshap
  summary: A fast implementation of TreeSHAP algorithm.
  license: BSD-2-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
